consul:
  image: consul
  ports:
    - "8400:8400"
    - "8500:8500"
    - "8600:8600"

service-b:
  image:  spring-cloud-consul-example/service-b
  links:
    - "consul"

service-a:
  image:  spring-cloud-consul-example/service-a
  environment:
    - SPRING_APPLICATION_NAME=service-a
    - SPRING_APPLICATION_INSTANCE={{.Task.Slot}}
  links:
    - "consul"
    - "service-b"

admin-dashboard:
  image:  spring-cloud-consul-example/admin-dashboard
  ports:
    - "8040:8040"
  links:
    - "service-a"
    - "service-b"
